<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXChCNxs\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXChCNxs/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXChCNxs.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXChCNxs\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerXChCNxs\App_KernelDevDebugContainer([
    'container.build_hash' => 'XChCNxs',
    'container.build_id' => '7139f955',
    'container.build_time' => 1657033988,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXChCNxs');
